name: List files
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List all the files
        run: |
          echo "Listing all the files in the repository"
          find . -type f \
            ! -path "./.github/*" \
            ! -path "./.git/*" \
            ! -name ".gitignore" \
            
